language: python
bundler_args: --without development
before_install:
  - rm Gemfile.lock || true
  - sudo apt-get update && sudo apt-get install -y rubygems
  - sudo gem install bundler colorize
sudo: required
python:
  - 2.7
script: sudo bundle exec rake test
